# Generated by Django 3.0 on 2020-11-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='amount',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transactions',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
