# Generated by Django 3.0 on 2021-01-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0003_auto_20210103_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='c_name',
            new_name='cust_name',
        ),
    ]
